//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemplosLambda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alunos_CursosAgendados
    {
        public long ID { get; set; }
        public int IdCursosAgendados { get; set; }
        public int IdAluno { get; set; }
    
        public virtual Alunos Alunos { get; set; }
        public virtual CursosAgendados CursosAgendados { get; set; }
    }
}
