//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemplosLambda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alunos
    {
        public Alunos()
        {
            this.Alunos_CursosAgendados = new HashSet<Alunos_CursosAgendados>();
        }
    
        public int ID { get; set; }
        public int IdPessoa { get; set; }
        public string Cargo { get; set; }
        public string Empresa { get; set; }
    
        public virtual ICollection<Alunos_CursosAgendados> Alunos_CursosAgendados { get; set; }
        public virtual Pessoas Pessoas { get; set; }
    }
}
