//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemplosLambda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificacoes
    {
        public int ID { get; set; }
        public int IdProfessor { get; set; }
        public string Descricao { get; set; }
        public string EmpresaEmissora { get; set; }
    
        public virtual Professores Professores { get; set; }
    }
}
