//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemplosLambda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoas
    {
        public Pessoas()
        {
            this.Alunos = new HashSet<Alunos>();
            this.Professores = new HashSet<Professores>();
        }
    
        public int ID { get; set; }
        public string PrimeiroNome { get; set; }
        public string UltimoNome { get; set; }
        public string Endereco { get; set; }
        public System.DateTime DtNascimento { get; set; }
    
        public virtual ICollection<Alunos> Alunos { get; set; }
        public virtual ICollection<Professores> Professores { get; set; }
    }
}
